OpenCabinetDrawer:
  cfg: "configs/bc/2tasks3.py"
  ckpt: "models/OpenCabinetDrawer.ckpt"
OpenCabinetDoor:
  cfg: "configs/bc/2tasks3.py"
  ckpt: "models/OpenCabinetDrawer.ckpt"
PushChair:
  cfg: "configs/bc/2tasks3.py"
  ckpt: "models/OpenCabinetDrawer.ckpt"
MoveBucket:
  cfg: "configs/bc/2tasks3.py"
  ckpt: "models/OpenCabinetDrawer.ckpt"
