on: [push]

jobs:
  maniskil_test:
    runs-on: ubuntu-latest
    name: Run ManiSkill test in Sapien
    steps:
      - uses: actions/checkout@v2
      - name: checkout modified ManiSkill repo
        uses: actions/checkout@v2
        with:
          repository: 'warp-art/ManiSkill'
          ref: "feature/run-basic"
          token: ${{ secrets.PAT_TOKEN }}
          path: 'ManiSkill'
      - name: Private actions checkout
        uses: daspn/private-actions-checkout@v2
        with:
          actions_list: '["warp-art/action-buildtest@main"]'
          checkout_base_path: ./.github/actions
          app_id: ${{ secrets.APP_ID }}
          app_private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: ./.github/actions/action-buildtest
        with:
          account_id: action_test
          api_key: ${{ secrets.WARP_API_KEY}}
