on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2
      - name: Private actions checkout
        uses: daspn/private-actions-checkout@v2
        with:
          actions_list: '["warp-art/action-buildtest@main"]'
          checkout_base_path: ./.github/actions
          app_id: ${{ secrets.APP_ID }}
          app_private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: ./.github/actions/action-buildtest
        with:
          who-to-greet: 'Mona the Octocat'
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
