on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2
      - name: Checkout warp-art/action-buildtest
        uses: actions/checkout@v2
        with:
          repository: warp-art/awesome-action
          ref: refs/heads/master
          # GitHub's personal access token with access to `my-organization/awesome-action`
          token: ${{secrets.APP_KEY}}
          persist-credentials: false
          path: ./.github/actions/action-buildtest
      - uses: ./.github/actions/action-buildtest
        with:
          who-to-greet: 'Mona the Octocat'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
