on: [push]

jobs:
  maniskil_test:
    runs-on: ubuntu-latest
    name: Run ManiSkill test in Sapien
    steps:
      - uses: actions/checkout@v2
      - name: checkout modified ManiSkill repo
        uses: actions/checkout@v2
        with:
          repository: 'warp-art/ManiSkill'
          ref: "feature/run-basic"
          token: ${{ secrets.PAT_TOKEN }}
          path: 'ManiSkill'
      - name: Private actions checkout
        uses: daspn/private-actions-checkout@v2
        with:
          actions_list: '["warp-art/action-buildtest@main"]'
          checkout_base_path: ./.github/actions
          app_id: ${{ secrets.APP_ID }}
          app_private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: Download model
        run: |
          aws s3 cp s3://maniskill-models/OpenCabinetDrawer.ckpt .
      - uses: ./.github/actions/action-buildtest
        with:
          account_id: action_test
